defaults:
  - model: midi
  - dataset: lakh-midi
  - logger: wandb

experiment_name: base
seed: 42

trainer:
  _target_: lightning.Trainer
  logger: ${logger}
  deterministic: true
  max_epochs: 10
  max_time: 00:03:00:00
  callbacks: # "-" makes callbacks a list
    # Periodic Checkpoint
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      dirpath: ${paths.checkpoints_dir}
      filename: periodic-epoch={epoch}-val_loss={val/loss:.2f}
      auto_insert_metric_name: false
      save_last: true
    
    # Best Checkpoint
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      dirpath: ${paths.checkpoints_dir}
      filename: best-epoch={epoch}-val_loss={val/loss:.2f}
      auto_insert_metric_name: false
      save_top_k: 3
      monitor: val/loss
      mode: min
    
    # LR Monitor
    - _target_: lightning.pytorch.callbacks.LearningRateMonitor
      logging_interval: epoch
      log_momentum: true
    
    # Batch Size Finder
    - _target_: lightning.pytorch.callbacks.BatchSizeFinder

    # Generation
    - _target_: callbacks.generation.SampleGeneration
      converter: ${evaluator.converter}
      sample_dir: ${paths.sample_dir}
      seq_len: ${dataset.max_seq_len}
      num_samples: 3
#    - _target_: lightning.pytorch.callbacks.DeviceStatsMonitor # logs quite a lot of data

evaluator:
  _target_: evaluator.Evaluator
  logger: ${logger}
  eval_dir: ${paths.eval_dir}
  ref_data_dir: ${paths.data_dir}/MIDITok/processed
  num_samples: 15000 # should be 10-50 times embedding dim, CLaMP 2 has embedding dim 768
  seq_len: ${dataset.max_seq_len}
  batch_size: ${dataset.batch_size}
  converter:
    _target_: utils.AudioConverter
    tokenizer: ${dataset.tokenizer}
  metrics:
    - _target_: metrics.fmd.FMD
      references_dir: ${paths.eval_dir}/ref
      sample_dir: ${paths.eval_dir}/samples
      cache_dir: ${paths.fmd_cache_dir}
    - _target_: metrics.common.CommonMetrics
      references_dir: ${paths.eval_dir}/ref
      sample_dir: ${paths.eval_dir}/samples
      metrics:
        - "Drum in Pattern Rate"
        - "Drum Pattern Consistency"
#        - "Empty Beat Rate" # seems to take a long time or crash
#        - "Empty Measure Rate" # seems to take a long time or crash
        - "Groove Consistency"
        - "Num of Pitch Classes Used"
        - "Num of Pitches Used"
        - "Pitch Class Entropy"
        - "Pitch Entropy"
        - "Pitch in Scale Rate"
        - "Pitch Range"
#        - "Polyphony" # seems to crash
#        - "Polyphony Rate" # seems to crash
        - "Scale Consistency"

paths:
  # path to root directory
  # this requires PROJECT_ROOT environment variable to exist
  # you can replace it with "." if you want the root to be the current working directory
  root_dir: "." # ${oc.env:PROJECT_ROOT:.}

  # path to data directory
  data_dir: ${paths.root_dir}/data

  # path to output directory, created dynamically by hydra
  # path generation pattern is specified in `configs/hydra/default.yaml`
  # use it to store all files generated during the run, like ckpts and metrics
  output_dir: ${hydra:runtime.output_dir}

  # path to working directory
  work_dir: ${hydra:runtime.cwd}

  # checkpoint directory
  checkpoints_dir: ${paths.output_dir}/checkpoints/

  # directory for sample generation
  sample_dir: ${paths.output_dir}/samples/

  # directory for evaluation samples
  eval_dir: ${paths.output_dir}/eval

  # cache dir for FMD metric, only overridden for cluster run
  fmd_cache_dir: null