_target_: lightning.pytorch.loggers.wandb.WandbLogger
name: ${experiment_name}_${now:%Y-%m-%d_%H-%M-%S}
save_dir: "${paths.output_dir}"
offline: False
project: "symb-music-gen"
log_model: True # upload lightning ckpts
entity: "dl-2025" # set to name of your wandb team
