defaults:
  - lakh-MIDI

_target_: dataset.miditok.MIDITok
batch_size: 64
max_seq_len: 128
tokenizer:
  _target_: miditok.Octuple
  _args_:
    - _target_: miditok.TokenizerConfig
      num_velocities: 16
      use_programs: True
      use_velocities: True
      using_note_duration_tokens: True
      use_tempos: True
      use_time_signatures: True
      max_bar_embedding: 256