defaults:
  - lakh-MIDI-10k

_target_: dataset.miditok.MIDITok
batch_size: 1024
max_seq_len: 64
tokenizer:
  _target_: miditok.Octuple
  _args_:
    - _target_: miditok.TokenizerConfig
      use_programs: False
      use_velocities: False
      use_tempos: False
      use_time_signatures: False
      use_pitchdrum_tokens: False
      max_bar_embedding: 127