# conf/model/musicbert_diffusion.yaml
_target_: model.musicbert_diffusion.MusicBertDiffusion

mask_strategy:
  _target_: model.mask.NoteMasking

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0005
  weight_decay: 0.01

# Offsets shifted by +4 (Specials)
offsets: [4, 97, 133, 197]

net:
  # CHANGE HERE: Removed 'src.'
  _target_: net.musicbert.MusicBERT
  
  vocab_size: 266 
  hidden_dim: 256
  num_layers: 6
  num_heads: 8
  max_seq_len: 1024 
  tokens_per_note: 4