_target_: model.ours.OurModel

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0005

net:
  _target_: torch.nn.TransformerEncoder
  encoder_layer:
    _target_: torch.nn.TransformerEncoderLayer
    d_model: 8
    nhead: 8
  num_layers: 6

criterion:
  _target_: torch.nn.functional.mse_loss
  _partial_: true
