_target_: model.ours.OurModel

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0005

net:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: torch.nn.Linear # upscale to embedding space
      in_features: 8
      out_features: 256
    - _target_: torch.nn.ReLU
    - _target_: torch.nn.TransformerEncoder # transform
      encoder_layer:
        _target_: torch.nn.TransformerEncoderLayer
        d_model: 256
        nhead: 8
        batch_first: true
      num_layers: 6
    - _target_: torch.nn.Linear # downscale
      in_features: 256
      out_features: 2048 # 8 * 256
    - _target_: torch.nn.ReLU
    - _target_: net.nn.Octuple # format output
    - _target_: torch.nn.Softmax
      dim: -1

criterion:
  _target_: torch.nn.functional.cross_entropy
  _partial_: true
