_target_: model.schmubert.Schmubert

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0005

#net:
#  _target_: net.schmubert.Schmubert
#  _partial_: true

#criterion:
#  _target_: torch.nn.functional.cross_entropy
#  _partial_: true
