# @package _global_
# overrides for local runs

trainer:
  #  fast_dev_run: true
  max_epochs: 1
  limit_train_batches: 5
  limit_val_batches: 1
  limit_test_batches: 1
  callbacks:
    # Generation
    - _target_: callbacks.generation.SampleGeneration
      converter: ${evaluator.converter}
      sample_dir: ${paths.sample_dir}
      num_samples: 3
      seq_len: ${dataset.max_seq_len}
logger:
  offline: true
  log_model: false
dataset:
  batch_size: 16
  download_url: https://polybox.ethz.ch/index.php/s/MnQDB4opQdR7nat/download/lakh-midi-1k.tar.gz
evaluator:
  num_samples: 5
  num_references: 10