# @package _global_
# overrides for local runs

trainer:
  fast_dev_run: true
  max_epochs: 1
  limit_train_batches: 9
  limit_val_batches: 1
  limit_test_batches: 1
#  callbacks: # no callbacks in local runs
logger:
  offline: true
  log_model: false
dataset:
  batch_size: 16