# @package _global_
# overrides for local runs

trainer:
  max_epochs: 1
  fast_dev_run: true
  callbacks: # no callbacks in local runs
logger:
  offline: true
  log_model: false
dataset:
  batch_size: 16