# @package _global_
# overrides for local runs

trainer:
  max_epochs: 5

  #limit_train_batches: 20  # Only use 10 batches per epoch
  limit_val_batches: 50     # Only use 5 batches for validation
  #limit_test_batches: 200   # <--- ADD THIS LINE

  callbacks:
    generation:
      _target_: callbacks.generation.GenerationCallback
      tokenizer: ${dataset.tokenizer}
      sample_rate: 44100
      num_samples: 3
logger:
  offline: false
  log_model: true
dataset:
  batch_size: 128